function irRandom() {
  const paginas = [
    "cap1_part1.html",
    "cap2_part1.html",
    "cap3_part1.html",
    "cap4_part1.html",
    "cap5_part1.html",
    "cap6_part1.html",
    "cap7_part1.html",
    "cap8_part1.html",
    "cap9_part1.html",
    "cap10_part1.html",
    "cap11_part1.html",
    "cap12_part1.html",
    "cap13_part1.html",
    "cap14_part1.html",
    "cap15_part1.html",
    "cap16_part1.html",
    "cap17_part1.html",
    "cap18_part1.html",
    "cap19_part1.html",
    "cap20_part1.html",
    "cap21_part1.html",
    "cap22_part1.html",
    "cap23_part1.html",
    "cap1_part2.html",
    "cap2_part2.html",
    "cap3_part2.html",
    "cap4_part2.html",
    "cap5_part2.html",
    "cap6_part2.html",
    "cap7_part2.html",
    "cap8_part2.html",
    "cap9_part2.html",
    "cap10_part2.html",
    "cap11_part2.html",
    "cap12_part2.html",
    "cap13_part2.html",
    "cap14_part2.html",
    "cap15_part2.html",
    "cap16_part2.html",
    "cap17_part2.html",
    "cap18_part2.html",
    "cap19_part2.html"
  ];

  const random = Math.floor(Math.random() * paginas.length);
  window.location.href = paginas[random];
}